### ISSUE TITLE
Design Web-application

### ISSUE THREAD

**Issue by phoenixml** [tee2015/PROJECT2#2]
SiteMap

![sitemap 6](https://cloud.githubusercontent.com/assets/14360476/17834702/c1c31b58-678f-11e6-9274-91315915c752.jpg)

**Comment by phoenixml** [comment]
#Design
#Main Form
![mainform](https://cloud.githubusercontent.com/assets/14360476/17834671/7d0a7aa2-678e-11e6-87b4-6bfae6a0faee.png)

**Comment by tee2015** [comment]
Incident Report
![incident report](https://cloud.githubusercontent.com/assets/14360476/17834714/19057fe6-6790-11e6-9b88-365f091e696b.png)

**Comment by phoenixml** [comment]
Incident Report
![incident report](https://cloud.githubusercontent.com/assets/14360476/17834717/34a8d2e8-6790-11e6-8db8-b1c5fdcc0e4c.png)

**Comment by phoenixml** [comment]
After Hours Lift Check List
![Uploading LIFT Check.png…]()

**Comment by phoenixml** [comment]
Daily Check List
![daily check form](https://cloud.githubusercontent.com/assets/14360476/17834815/46e6fafc-6795-11e6-96f2-975fb674163d.png)

**Comment by phoenixml** [comment]
Hand over
![handover](https://cloud.githubusercontent.com/assets/14360476/17834864/1fdcf7de-6797-11e6-9a3a-a59af613df56.png)

**Comment by phoenixml** [comment]
Log Book
![logbook](https://cloud.githubusercontent.com/assets/14360476/17834878/da693284-6797-11e6-912c-40d6ea955ebd.png)

**Comment by phoenixml** [comment]
Guard Bulletin
![bulletin](https://cloud.githubusercontent.com/assets/14360476/17834901/a95304ee-6798-11e6-87c1-56491cbafa2e.png)
